# Generated by Django 3.0.2 on 2020-07-02 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feng_forum_upload', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uploadedmedia',
            options={'verbose_name': '被上传的多媒体', 'verbose_name_plural': '被上传的多媒体'},
        ),
        migrations.AddField(
            model_name='uploadedmedia',
            name='content',
            field=models.TextField(blank=True, max_length=500, verbose_name='描述'),
        ),
        migrations.AddField(
            model_name='uploadedmedia',
            name='name',
            field=models.CharField(blank=True, max_length=10, verbose_name='文件名'),
        ),
    ]
