# Generated by Django 3.0.2 on 2020-07-11 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feng_forum_upload', '0003_auto_20200702_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedmedia',
            name='is_icon',
            field=models.BooleanField(default=False),
        ),
    ]
