version: '3.5'

services:
  webprod:
    image: harryfyx/feng_forum:latest
    command: gunicorn feng_forum.wsgi:application --bind 0.0.0.0:8000 --access-logfile gunicorn_log
    expose:
      - 8000
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    env_file:
      - ./.env.prod
    depends_on:
      - dbprod
  dbprod:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
  nginxprod:
    build: ./nginx
    ports:
      - 80:80
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    depends_on:
      - webprod

volumes:
  postgres_data:
  static_volume:
  media_volume: