# Generated by Django 3.0.2 on 2020-07-02 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feng_forum_user', '0007_auto_20200702_1643'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='forumaccount',
            options={'ordering': ['user'], 'verbose_name': '账户', 'verbose_name_plural': '账户'},
        ),
    ]
