# Generated by Django 3.0.2 on 2020-07-02 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feng_forum_user', '0008_auto_20200702_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumaccount',
            name='following',
            field=models.ManyToManyField(help_text='用户关注的人', null=True, to='feng_forum_user.ForumAccount'),
        ),
    ]
