# Generated by Django 3.0.2 on 2020-07-05 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feng_forum_user', '0011_notification'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['forumaccount'], 'verbose_name': '提示信息', 'verbose_name_plural': '提示信息'},
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='account',
            new_name='forumaccount',
        ),
        migrations.AlterField(
            model_name='notification',
            name='link',
            field=models.URLField(blank=True, verbose_name='信息链接'),
        ),
    ]
