# Generated by Django 3.0.2 on 2020-07-07 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feng_forum_user', '0012_auto_20200705_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=models.CharField(max_length=25, verbose_name='信息内容'),
        ),
    ]
