# Generated by Django 3.0.2 on 2020-07-07 21:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('feng_forum_user', '0014_auto_20200707_2112'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-sent_datetime'], 'verbose_name': '提示信息', 'verbose_name_plural': '提示信息'},
        ),
        migrations.AddField(
            model_name='notification',
            name='sent_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='发送时间'),
        ),
    ]
