# Generated by Django 3.0.2 on 2020-07-07 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feng_forum_user', '0020_auto_20200707_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='read',
            field=models.BooleanField(default=False, verbose_name='已读'),
        ),
    ]
