# Generated by Django 3.0.2 on 2020-06-28 02:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DSet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID to query the DObject', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('parents', models.ManyToManyField(blank=True, help_text='The DSets it is a subset of.', to='main_rest.DSet')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
