# Generated by Django 3.0.2 on 2020-07-02 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('feng_forum_upload', '0001_initial'),
        ('feng_forum_user', '0007_auto_20200702_1643'),
    ]

    operations = [
        migrations.CreateModel(
            name='MicroForumThread',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='帖子的内容')),
                ('post_datetime', models.DateTimeField(verbose_name='发帖时间')),
                ('referenced', models.ManyToManyField(help_text='@ 到的账户。', to='feng_forum_user.ForumAccount')),
                ('reply_to', models.ForeignKey(blank=True, help_text='作为什么微帖的回复。', on_delete=django.db.models.deletion.CASCADE, to='feng_forum_main.MicroForumThread')),
                ('uploaded_media', models.ManyToManyField(help_text='帖子内包括的多媒体。', to='feng_forum_upload.UploadedMedia')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ForumThread',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='帖子的内容')),
                ('post_datetime', models.DateTimeField(verbose_name='发帖时间')),
                ('referenced', models.ManyToManyField(help_text='@ 到的账户。', to='feng_forum_user.ForumAccount')),
                ('reply_to', models.ForeignKey(blank=True, help_text='作为什么帖子的回复。', on_delete=django.db.models.deletion.CASCADE, to='feng_forum_main.ForumThread')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
