# Generated by Django 3.0.2 on 2020-07-02 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feng_forum_upload', '0002_auto_20200702_1657'),
        ('feng_forum_main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='forumthread',
            options={'verbose_name': '贴子', 'verbose_name_plural': '贴子'},
        ),
        migrations.AlterModelOptions(
            name='microforumthread',
            options={'verbose_name': '微贴', 'verbose_name_plural': '微贴'},
        ),
        migrations.AddField(
            model_name='forumthread',
            name='title',
            field=models.CharField(default='未命名', max_length=15, verbose_name='标题'),
        ),
        migrations.AlterField(
            model_name='forumthread',
            name='content',
            field=models.TextField(verbose_name='贴子的内容'),
        ),
        migrations.AlterField(
            model_name='forumthread',
            name='post_datetime',
            field=models.DateTimeField(verbose_name='发贴时间'),
        ),
        migrations.AlterField(
            model_name='forumthread',
            name='reply_to',
            field=models.ForeignKey(blank=True, help_text='作为什么贴子的回复。', on_delete=django.db.models.deletion.CASCADE, to='feng_forum_main.ForumThread'),
        ),
        migrations.AlterField(
            model_name='microforumthread',
            name='content',
            field=models.TextField(verbose_name='贴子的内容'),
        ),
        migrations.AlterField(
            model_name='microforumthread',
            name='post_datetime',
            field=models.DateTimeField(verbose_name='发贴时间'),
        ),
        migrations.AlterField(
            model_name='microforumthread',
            name='reply_to',
            field=models.ForeignKey(blank=True, help_text='作为什么微贴的回复。', on_delete=django.db.models.deletion.CASCADE, to='feng_forum_main.MicroForumThread'),
        ),
        migrations.AlterField(
            model_name='microforumthread',
            name='uploaded_media',
            field=models.ManyToManyField(help_text='贴子内包括的多媒体。', to='feng_forum_upload.UploadedMedia'),
        ),
    ]
