# Generated by Django 3.0.2 on 2020-07-02 17:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('feng_forum_main', '0002_auto_20200702_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumthread',
            name='user',
            field=models.ForeignKey(help_text='发送的用户。', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forumthread_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='microforumthread',
            name='user',
            field=models.ForeignKey(help_text='发送的用户。', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='microforumthread_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='forumthread',
            name='referenced',
            field=models.ManyToManyField(blank=True, help_text='@ 到的用户。', related_name='forumthread_referenced', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='microforumthread',
            name='referenced',
            field=models.ManyToManyField(blank=True, help_text='@ 到的用户。', related_name='microforumthread_referenced', to=settings.AUTH_USER_MODEL),
        ),
    ]
