# Generated by Django 3.0.2 on 2020-07-02 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feng_forum_main', '0004_auto_20200702_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumthread',
            name='title',
            field=models.CharField(default='未命名', max_length=15, null=True, verbose_name='标题'),
        ),
    ]
