# Generated by Django 3.0.2 on 2020-07-02 19:04

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feng_forum_main', '0005_auto_20200702_1817'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='未命名', max_length=15, null=True, verbose_name='标题')),
            ],
            options={
                'verbose_name': '贴吧',
                'verbose_name_plural': '贴吧',
                'ordering': ['title'],
            },
        ),
        migrations.AlterField(
            model_name='forumthread',
            name='post_datetime',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='发贴时间'),
        ),
        migrations.AlterField(
            model_name='microforumthread',
            name='post_datetime',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='发贴时间'),
        ),
        migrations.AddField(
            model_name='forumthread',
            name='topic',
            field=models.ForeignKey(help_text='本帖所在的贴吧。', null=True, on_delete=django.db.models.deletion.CASCADE, to='feng_forum_main.Topic'),
        ),
        migrations.AddField(
            model_name='microforumthread',
            name='topic',
            field=models.ForeignKey(help_text='本微帖所在的贴吧。', null=True, on_delete=django.db.models.deletion.CASCADE, to='feng_forum_main.Topic'),
        ),
    ]
