# Generated by Django 3.0.2 on 2020-07-02 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feng_forum_main', '0007_auto_20200702_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='microforumthread',
            name='reply_to',
            field=models.ForeignKey(blank=True, help_text='作为什么微贴的回复。', null=True, on_delete=django.db.models.deletion.CASCADE, to='feng_forum_main.MicroForumThread'),
        ),
    ]
