# Generated by Django 3.0.2 on 2020-07-03 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feng_forum_upload', '0003_auto_20200702_1731'),
        ('feng_forum_main', '0008_auto_20200702_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='microforumthread',
            name='uploaded_media',
            field=models.ManyToManyField(blank=True, help_text='贴子内包括的多媒体。', to='feng_forum_upload.UploadedMedia'),
        ),
    ]
