# Generated by Django 3.0.2 on 2020-07-03 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feng_forum_main', '0010_forumthread_new'),
    ]

    operations = [
        migrations.AddField(
            model_name='microforumthread',
            name='new',
            field=models.BooleanField(default=False, verbose_name='新建'),
        ),
        migrations.AlterField(
            model_name='forumthread',
            name='new',
            field=models.BooleanField(default=False, verbose_name='新建'),
        ),
    ]
