# Generated by Django 3.0.2 on 2020-07-05 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feng_forum_main', '0011_auto_20200703_0515'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumthread',
            name='deleted',
            field=models.BooleanField(default=False, verbose_name='已删除'),
        ),
    ]
