# Generated by Django 3.0.2 on 2020-07-08 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feng_forum_main', '0012_forumthread_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumthread',
            name='priviledged',
            field=models.BooleanField(default=False, verbose_name='高访问级别'),
        ),
    ]
